##  -*- python -*-  
# db file automatically generated by genconf on: Wed Nov 12 13:47:43 2014## insulates outside world against anything bad that could happen
## also prevents global scope pollution
def _fillCfgDb():
    from GaudiKernel.Proxy.ConfigurableDb import CfgDb

    # get a handle on the repository of Configurables
    cfgDb = CfgDb()

    # populate the repository with informations on Configurables 

    cfgDb.add( configurable = 'VertexCompare',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'UTTrackMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TTTrackMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackVertexMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackVeloOverlapMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackV0Monitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackTuple',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackTune',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackTimingMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackPV2HalfAlignMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackParticleMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackMuonMatchMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackMonitorNT',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackITOverlapMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackFitMatchMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackExpectedHitsXYZTool',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackDiMuonMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackCaloMatchMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'TrackAlignMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'STYAlignMagOff',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'STEfficiency',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'STCoordinates',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'PVSplit',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'PVResMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'PitchResTool',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'OTYAlignMagOff',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'OTTrackMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'OTHitEfficiencyMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'OTCoordinates',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'ITTrackMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'HitEffPlotter',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    cfgDb.add( configurable = 'AlignmentOnlineMonitor',
               package = 'TrackMonitors',
               module  = 'TrackMonitors.TrackMonitorsConf',
               lib     = 'TrackMonitors' )
    return #_fillCfgDb
# fill cfgDb at module import...
try:
    _fillCfgDb()
    #house cleaning...
    del _fillCfgDb
except Exception,err:
    print "Py:ConfigurableDb   ERROR Problem with [%s] content!" % __name__
    print "Py:ConfigurableDb   ERROR",err
    print "Py:ConfigurableDb   ERROR   ==> culprit is package [TrackMonitors] !"
